server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 
  rabbitmq:
    host: toad.rmq.cloudamqp.com
    port: 5672
    username: wxyerahj
    password: cTP153V8xe3DsuDcWdWIuVgeBLPPpK_c
    virtual-host: wxyerahj
    ssl:
      enabled: false
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

auth:
  jwtSecret: 817cff65-0402-46fb-ba27-7c6809959fd1
  jwtExpiration: 300000
  