server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
    password: admin 
    driver-class-name: org.postgresql.Driver
    
  rabbitmq:
    host: toad.rmq.cloudamqp.com
    port: 5672
    username: wxyerahj
    password: cTP153V8xe3DsuDcWdWIuVgeBLPPpK_c
    virtual-host: wxyerahj
    ssl:
      enabled: false
  
  jpa:
    hibernate:
      #ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      
flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true
  
auth:
  jwtSecret: 817cff65-0402-46fb-ba27-7c6809959fd1
  jwtExpiration: 300000
