server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      
auth:
  username:  
